import React, { createContext, useContext, useState, ReactNode } from 'react';

interface Language {
  code: string;
  name: string;
  flagComponent: string;
}

export const languages: Language[] = [
  { code: 'no', name: 'Norsk', flagComponent: 'norwegian' },
  { code: 'en', name: 'English', flagComponent: 'british' }
];

interface Translations {
  [key: string]: string;
}

const translations: { [key: string]: Translations } = {
  no: {
    // Navigation
    'nav.home': 'Hjem',
    'nav.about': 'Om oss',
    'nav.more': 'Mer',
    'nav.aboutPrisPilot': 'Om PrisPilot',
    'nav.howItWorks': 'Hvordan det fungerer',
    'nav.contact': 'Kontakt oss',
    'nav.blog': 'Blogg',
    'nav.settings': 'Innstillinger',
    'nav.language': 'Språk',
    'nav.theme': 'Tema',

    // Navigation specific
    'navigation.backToOverview': 'Tilbake til oversikt',
    'navigation.compareAndFind': 'Sammenlign og finn beste tilbud',

    // Terms
    'terms.backToHome': 'Tilbake til hjem',
    'terms.title': 'Vilkår og betingelser',
    'terms.lastUpdated': 'Sist oppdatert',
    'terms.acceptance.title': 'Aksept av vilkår',
    'terms.acceptance.content': 'Ved å bruke PrisPilot godtar du disse vilkårene og betingelsene.',
    'terms.serviceDescription.title': 'Tjenestebeskrivelse',
    'terms.serviceDescription.intro': 'PrisPilot tilbyr følgende tjenester:',
    'terms.serviceDescription.feature1': 'Prissammenligning av strøm, mobil, internett og andre tjenester',
    'terms.serviceDescription.feature2': 'Tilbudshenting og formidling til tredjepartsleverandører',
    'terms.serviceDescription.feature3': 'Informasjon og veiledning om ulike produkter og tjenester',
    'terms.userResponsibility.title': 'Brukeransvar',
    'terms.userResponsibility.intro': 'Som bruker er du ansvarlig for:',
    'terms.userResponsibility.item1': 'Å oppgi korrekte og oppdaterte opplysninger',
    'terms.userResponsibility.item2': 'Å bruke tjenesten i henhold til gjeldende lover og regler',
    'terms.userResponsibility.item3': 'Å ikke misbruke eller manipulere tjenesten',
    'terms.userResponsibility.item4': 'Å beskytte dine egne innloggingsopplysninger',
    'terms.informationAccuracy.title': 'Nøyaktighet av informasjon',
    'terms.informationAccuracy.content': 'Vi streber etter å holde all informasjon oppdatert og nøyaktig, men kan ikke garantere fullstendig nøyaktighet til enhver tid.',
    'terms.thirdPartyServices.title': 'Tredjepartstjenester',
    'terms.thirdPartyServices.content': 'Når du bruker våre tjenester kan du bli videreført til tredjepartsleverandører. Vi er ikke ansvarlige for deres vilkår eller tjenester.',
    'terms.limitationOfLiability.title': 'Ansvarsbegrensning',
    'terms.limitationOfLiability.content': 'PrisPilot kan ikke holdes ansvarlig for indirekte tap eller skader som følge av bruk av våre tjenester.',
    'terms.changes.title': 'Endringer i vilkår',
    'terms.changes.content': 'Vi forbeholder oss retten til å endre disse vilkårene. Endringer vil bli publisert på denne siden.',
    'terms.contact.title': 'Kontakt',
    'terms.contact.intro': 'For spørsmål om vilkårene kan du kontakte oss:',
    'terms.contact.email': 'E-post',
    'terms.contact.phone': 'Telefon',
    'terms.applicableLaw.title': 'Gjeldende lov',
    'terms.applicableLaw.content': 'Disse vilkårene er underlagt norsk lov og eventuelle tvister skal løses ved norske domstoler.',

    // Privacy
    'privacy.backToHome': 'Tilbake til hjem',
    'privacy.title': 'Personvernerklæring',
    'privacy.lastUpdated': 'Sist oppdatert',
    'privacy.introduction.title': 'Innledning',
    'privacy.introduction.content': 'Denne personvernerklæringen forklarer hvordan PrisPilot samler inn, bruker og beskytter dine personopplysninger.',
    'privacy.dataCollection.title': 'Datainnsamling',
    'privacy.dataCollection.userProvided.title': 'Opplysninger du oppgir',
    'privacy.dataCollection.userProvided.item1': 'Navn og kontaktinformasjon',
    'privacy.dataCollection.userProvided.item2': 'Forbruksdata og preferanser',
    'privacy.dataCollection.userProvided.item3': 'Kommunikasjon med kundeservice',
    'privacy.dataCollection.automatic.title': 'Automatisk innsamlede data',
    'privacy.dataCollection.automatic.item1': 'IP-adresse og enhetsinfo',
    'privacy.dataCollection.automatic.item2': 'Nettlesningsdata og cookies',
    'privacy.dataCollection.automatic.item3': 'Bruksmønstre og preferanser',
    'privacy.dataUsage.title': 'Bruk av data',
    'privacy.dataUsage.intro': 'Vi bruker dine data til følgende formål:',
    'privacy.dataUsage.item1': 'Å levere og forbedre våre tjenester',
    'privacy.dataUsage.item2': 'Å personalisere tilbud og anbefalinger',
    'privacy.dataUsage.item3': 'Å kommunisere med deg om våre tjenester',
    'privacy.dataUsage.item4': 'Å oppfylle juridiske forpliktelser',
    'privacy.dataUsage.item5': 'Å analysere og forbedre brukeropplevelsen',
    'privacy.dataSharing.title': 'Deling av data',
    'privacy.dataSharing.intro': 'Vi kan dele dine opplysninger med:',
    'privacy.dataSharing.item1': 'Partnere og leverandører som leverer tjenester på våre vegne',
    'privacy.dataSharing.item2': 'Tredjepartsleverandører for tilbudsformidling',
    'privacy.dataSharing.item3': 'Myndigheter når det kreves av lov',
    'privacy.dataSharing.item4': 'Andre parter med ditt uttrykkelige samtykke',
    'privacy.cookies.title': 'Informasjonskapsler (cookies)',
    'privacy.cookies.intro': 'Vi bruker cookies til:',
    'privacy.cookies.item1': 'Å huske dine preferanser og innstillinger',
    'privacy.cookies.item2': 'Å analysere hvordan nettsiden brukes',
    'privacy.cookies.item3': 'Å tilpasse innhold og annonser',
    'privacy.cookies.item4': 'Å forbedre sikkerheten på nettsiden',
    'privacy.cookies.control': 'Du kan kontrollere cookies gjennom nettleserinnstillingene dine.',
    'privacy.dataSecurity.title': 'Datasikkerhet',
    'privacy.dataSecurity.content': 'Vi implementerer tekniske og organisatoriske tiltak for å beskytte dine personopplysninger mot uautorisert tilgang, tap eller misbruk.',
    'privacy.rights.title': 'Dine rettigheter',
    'privacy.rights.intro': 'Du har følgende rettigheter vedrørende dine personopplysninger:',
    'privacy.rights.item1': 'Rett til innsyn i hvilke opplysninger vi har om deg',
    'privacy.rights.item2': 'Rett til å rette unøyaktige eller ufullstendige opplysninger',
    'privacy.rights.item3': 'Rett til sletting av dine personopplysninger',
    'privacy.rights.item4': 'Rett til å begrense behandlingen av dine opplysninger',
    'privacy.rights.item5': 'Rett til dataportabilitet',
    'privacy.rights.item6': 'Rett til å protestere mot behandling',
    'privacy.rights.item7': 'Rett til å trekke tilbake samtykke',
    'privacy.dataRetention.title': 'Oppbevaring av data',
    'privacy.dataRetention.content': 'Vi oppbevarer dine personopplysninger så lenge det er nødvendig for formålene beskrevet i denne erklæringen, eller som kreves av lov.',
    'privacy.policyChanges.title': 'Endringer i personvernerklæringen',
    'privacy.policyChanges.content': 'Vi kan oppdatere denne personvernerklæringen fra tid til annen. Endringer vil bli publisert på denne siden.',
    'privacy.contact.title': 'Kontakt oss',
    'privacy.contact.intro': 'For spørsmål om personvern kan du kontakte oss:',
    'privacy.contact.email': 'E-post',
    'privacy.contact.phone': 'Telefon',
    'privacy.contact.address': 'Adresse',
    'privacy.contact.complaint': 'Du kan også klage til Datatilsynet hvis du mener vi behandler dine personopplysninger feil.',

    // Hero Section
     'hero.title': 'Spar penger på strøm, mobil og forsikring – uten å løfte en finger.',
     'hero.subtitle': 'Vi gjør jobben for deg – du får de beste prisene uten å måtte sammenligne selv. Tjenesten er helt gratis, uten binding og fullt GDPR-sikret.',
     'hero.trust.free': '100% gratis',
     'hero.trust.nobinding': 'Ingen binding',
     'hero.trust.secure': 'Dine data er trygge hos oss',
     'hero.search.placeholder': 'Søk etter leverandør...',
     'hero.form.title': 'Få tilbud på minutter',
     'hero.form.subtitle': 'Fyll inn navn og telefon, og velg hva du ønsker å spare på. Vi sender deg forslag basert på din situasjon – helt uforpliktende.',
     'hero.form.usertype': 'Velg brukertype',
     'hero.form.private': 'Privat',
     'hero.form.business': 'Bedrift',
     'hero.form.name': 'Ditt Navn',
     'hero.form.phone': 'Telefonnummer',
     'hero.form.submit': 'FÅ TILBUD GRATIS',
     'hero.form.submitting': 'Sender...',
     'hero.form.consent': 'Ved å melde deg på godtar du våre',
     'hero.form.terms': 'vilkår og personvernpolicy',
     'hero.form.privacy': 'vilkår og personvernpolicy',

     // Index page
     'index.partners.title': 'Våre partnere',
     'index.partners.subtitle': 'Vi sammenligner tilbud fra ledende leverandører',
     'index.services.title': 'Alle tjenester',
     'index.services.subtitle': 'Vi sammenligner priser på alle disse områdene',
     'index.services.viewPrices': 'Se priser',

    // Categories
     'categories.strom.title': 'Strøm',
     'categories.strom.description': 'Sammenlign strømpriser',
     'categories.mobil.title': 'Mobil',
     'categories.mobil.description': 'Finn beste mobilabonnement',
     'categories.forsikring.title': 'Forsikring',
     'categories.forsikring.description': 'Sammenlign forsikringer',
     'categories.internett.title': 'Internett',
     'categories.internett.description': 'Finn beste internettilbud',
     'categories.lan.title': 'Lån',
     'categories.lan.description': 'Sammenlign låntilbud',
     'categories.boligalarm.title': 'Boligalarm',
     'categories.boligalarm.description': 'Finn beste sikkerhetssystem',
     'categories.tvPakker.title': 'TV Pakker',
     'categories.tvPakker.description': 'Sammenlign TV-pakker',
     'categories.handverkere.title': 'Håndverkere',
     'categories.handverkere.description': 'Finn kvalifiserte håndverkere',
     'categories.renhold.title': 'Renhold',
     'categories.renhold.description': 'Finn renholdstjenester',

    // Insurance specific
    'insurance.selectCategory': 'Velg kategori',
    'insurance.all': 'Alle',
    'insurance.allDescription': 'Vis alle forsikringer',
    'insurance.home': 'Boligforsikring',
    'insurance.homeDescription': 'Forsikring for bolig og innbo',
    'insurance.vehicle': 'Bilforsikring',
    'insurance.vehicleDescription': 'Forsikring for bil og motorsykkel',
    'insurance.person': 'Personforsikring',
    'insurance.personDescription': 'Livs- og personforsikring',
    'insurance.pets': 'Dyreforsikring',
    'insurance.petsDescription': 'Forsikring for kjæledyr',

    // TV packages specific
    'tv.selectCategory': 'Velg kategori',
    'tv.all': 'Alle',
    'tv.allDescription': 'Vis alle TV-pakker',
    'tv.standard': 'Standard',
    'tv.standardDescription': 'Grunnleggende TV-pakker',
    'tv.streaming': 'Streaming',
    'tv.streamingDescription': 'Strømmetjenester og on-demand',
    'tv.sport': 'Sport',
    'tv.sportDescription': 'Sportspakker og kanaler',
    'tv.flexible': 'Fleksibel',
    'tv.flexibleDescription': 'Fleksible TV-løsninger',
    'tv.cabin': 'Hytte',
    'tv.cabinDescription': 'TV-pakker for hytta',
    'tv.combo': 'Kombipakker',
    'tv.comboDescription': 'TV, internett og telefon',
    'tv.extras': 'Tillegg',
    'tv.extrasDescription': 'Tilleggstjenester og premium kanaler',

    // Loan specific
    'loan.selectCategory': 'Velg kategori',
    'loan.all': 'Alle',
    'loan.showAllOffers': 'Vis alle lånetilbud',
    'loan.unsecuredLoans': 'Usikrede lån',
    'loan.consumerLoan': 'Forbrukslån uten sikkerhet',
    'loan.refinanceDebt': 'Refinansiering',
    'loan.refinancing': 'Samle eksisterende gjeld',
    'loan.securedHomeLoan': 'Boliglån',
    'loan.homeLoan': 'Lån med pant i bolig',
    'loan.carLoan': 'Billån',
    'loan.vehicleFinancing': 'Finansiering av kjøretøy',

    // Alarm specific
    'alarm.selectCategory': 'Velg kategori',
    'alarm.all': 'Alle',
    'alarm.allDescription': 'Vis alle alarmsystemer',
    'alarm.intrusion': 'Innbrudd',
    'alarm.intrusionDescription': 'Innbruddsalarm og overvåking',
    'alarm.fire': 'Brann',
    'alarm.fireDescription': 'Brannalarm og røykvarslere',
    'alarm.water': 'Vann',
    'alarm.waterDescription': 'Vannlekkasje og fuktvarslere',
    'alarm.camera': 'Kamera',
    'alarm.cameraDescription': 'Overvåkingskameraer',
    'alarm.smart': 'Smart',
    'alarm.smartDescription': 'Smarte alarmsystemer',

     // How it works
     'howItWorks.title': 'Hvordan PrisPilot fungerer',
     'howItWorks.subtitle': 'Tre enkle steg til bedre avtaler og lavere priser på strøm, mobil, internett og forsikring.',
     'howItWorks.step1.number': 'STEG 1',
     'howItWorks.step1.title': 'Fortell oss om dine behov',
     'howItWorks.step1.description': 'Fyll ut et enkelt skjema med informasjon om din nåværende situasjon og preferanser.',
     'howItWorks.step1.detail1': 'Velg hvilken tjeneste du vil sammenligne',
     'howItWorks.step1.detail2': 'Oppgi din nåværende leverandør og avtale',
     'howItWorks.step1.detail3': 'Del kontaktinformasjon for personlige tilbud',
     'howItWorks.step2.number': 'STEG 2',
     'howItWorks.step2.title': 'Vi finner de beste tilbudene',
     'howItWorks.step2.description': 'Våre eksperter sammenligner hundrevis av tilbud fra ledende leverandører for å finne det som passer deg best.',
     'howItWorks.step2.detail1': 'Sammenligning av priser og vilkår',
     'howItWorks.step2.detail2': 'Vurdering basert på dine spesifikke behov',
     'howItWorks.step2.detail3': 'Kvalitetskontroll av alle anbefalinger',
     'howItWorks.step3.number': 'STEG 3',
     'howItWorks.step3.title': 'Du mottar personlige anbefalinger',
     'howItWorks.step3.description': 'Få skreddersydde tilbud direkte i telefonen eller på e-post, helt gratis og uten forpliktelser.',
     'howItWorks.step3.detail1': 'Personlige tilbud tilpasset dine behov',
     'howItWorks.step3.detail2': 'Transparent sammenligning av alternativer',
     'howItWorks.step3.detail3': 'Støtte gjennom hele prosessen',
     'howItWorks.cta.title': 'Klar til å spare penger?',
     'howItWorks.cta.subtitle': 'La oss hjelpe deg med å finne bedre avtaler på dine daglige tjenester.',
     'howItWorks.cta.button': 'Få tilbud gratis',

    // Services in header
    'services.strom': 'Strøm',
    'services.internett': 'Internett',
    'services.mobil': 'Mobil',
    'services.tv-pakker': 'TV-pakker',
    'services.forsikring': 'Forsikring',
    'services.lan': 'Lån',
    'services.boligalarm': 'Boligalarm',
    'services.handverkere': 'Håndverkere',
    'services.renhold': 'Renhold',

    // Internet specific
    'internet.selectCategory': 'Velg kategori',
    'internet.all': 'Alle',
    'internet.allDescription': 'Vis alle internettabonnementer',
    'internet.fiber': 'Fiber',
    'internet.fiberDescription': 'Høyhastighets fiberinternet',
    'internet.adsl': 'ADSL',
    'internet.adslDescription': 'ADSL-basert internett',
    'internet.mobile': 'Mobilt internett',
    'internet.mobileDescription': 'Internett via mobilnettet',
    'internet.business': 'Bedrift',
    'internet.businessDescription': 'Internett for bedrifter',

    // CTA
    'cta.getOffers': 'Få tilbud',
    'cta.compare': 'Sammenlign',
    'cta.signUp': 'Meld deg på',
    'cta.getQuote': 'Få tilbud',
    'cta.contactProvider': 'Kontakt leverandør',
    'cta.viewDetails': 'Se detaljer',
    'cta.selectOffer': 'Velg tilbud',
    'cta.backToTop': 'Tilbake til toppen',

    // Categories
    'categoryName.mobil': 'Mobil',
    'categoryName.strom': 'Strøm',
    'categoryName.internett': 'Internett',
    'categoryName.forsikring': 'Forsikring',
    'categoryName.lan': 'Lån',
    'categoryName.boligalarm': 'Boligalarm',
    'categoryName.tv-pakker': 'TV-pakker',
    'categoryName.handverkere': 'Håndverkere',
    'categoryName.renhold': 'Renhold',

    // Category specific
    'category.viewPrices': 'Se priser',

    // Mobile specific
    'mobile.selectCategory': 'Velg kategori',
    'mobile.all': 'Alle',
    'mobile.allDescription': 'Vis alle mobilabonnementer',
    'mobile.lowPrice': 'Lavpris',
    'mobile.lowPriceDescription': 'Rimelige abonnementer',
    'mobile.family': 'Familie',
    'mobile.familyDescription': 'Familieabonnementer',
    'mobile.unlimited': 'Ubegrenset',
    'mobile.unlimitedDescription': 'Ubegrenset data',
    'mobile.business': 'Bedrift',
    'mobile.businessDescription': 'Bedriftsabonnementer',

    // Electricity specific
    'electricity.selectCategory': 'Filtrer på avtaletype',
    'electricity.all': 'Alle',
    'electricity.allDescription': 'Vis alle strømavtaler',
    'electricity.spot': 'Spotpris',
    'electricity.spotDescription': 'Variable priser følger markedet',
    'electricity.fixed': 'Fastpris',
    'electricity.fixedDescription': 'Fastpris i perioder',
    'electricity.green': 'Grønn strøm',
    'electricity.greenDescription': 'Miljøvennlige alternativer',
    'electricity.business': 'Bedrift',
    'electricity.businessDescription': 'Strøm til bedrifter',
    'electricity.variableDescription': 'Variabel pris uten binding',
    'electricity.residentialDescription': 'Strøm til boliger og leiligheter',
    'electricity.cabinDescription': 'Strøm til hytter og fritidsboliger',

    // Power contract types
    'power.contractTypes.all': 'Alle',
    'power.contractTypes.spot': 'Spotpris',
    'power.contractTypes.fixed': 'Fastpris',
    'power.contractTypes.variable': 'Variabel',
    'power.contractTypes.green': 'Grønn strøm',
    'power.contractTypes.residential': 'Boligstrøm',
    'power.contractTypes.cabin': 'Hyttestrøm',

    // Power related
    'power.howMuchElectricity': 'Hvor mye strøm bruker du årlig?',
    'power.averageConsumption': 'Gjennomsnittlig årsforbruk',
    'power.selectMunicipality': 'Velg din kommune',
    'power.searchMunicipality': 'Søk etter kommune...',
    'power.filterContractType': 'Filtrer på avtaletype',
    'power.showMatchingOffers': 'Vis {{count}} tilbud',
    'power.resetFilters': 'Nullstill filtre',

    // Filters
    'filters.title': 'Filtrer',
    'filters.clear': 'Tøm',
    'filters.sort': 'Sorter',
    'filters.offersFound': 'tilbud funnet',
    'filters.labels.provider': 'Leverandør',
    'filters.labels.speed': 'Hastighet',
    'filters.labels.price': 'Pris',
    'filters.labels.operator': 'Operatør',
    'filters.labels.supplier_name': 'Leverandør',
    'filters.labels.municipality': 'Kommune',
    'filters.labels.priceElectricity': 'Pris (øre/kWh)',
    'filters.labels.contract_length': 'Avtaleperiode',
    'filters.labels.data_category': 'Datakategori',
    'filters.labels.insurance_type': 'Forsikringstype',
    'filters.labels.monthly_premium': 'Månedlig premie',
    'filters.labels.effective_rate': 'Effektiv rente (%)',
    'filters.labels.monthly_price': 'Månedspris',
    'filters.labels.plan_type': 'Plantype',
    'filters.labels.alarm_types': 'Alarmtyper',
    'filters.labels.installation_type': 'Installasjon',
    'filters.labels.response_service': 'Utrykning',
    'filters.labels.smart_features': 'Smarte funksjoner',
    'filters.labels.channels_count': 'Antall kanaler',
    'filters.labels.hourly_rate': 'Timepris',
    'filters.labels.service_type': 'Tjenestetype',
    'filters.labels.certification': 'Sertifisering',
    'filters.labels.cleaning_type': 'Rengjøringstype',
    'filters.labels.equipment_included': 'Utstyr inkludert',
    'filters.options.allProviders': 'Alle leverandører',
    'filters.options.selectProvider': 'Velg leverandør',
    'filters.options.all': 'Alle',
    'filters.options.search': 'Søk...',
    'filters.options.searchHint': 'Skriv inn kommunenavn',
    'filters.options.dataSmall': 'Lite data (under 5GB)',
    'filters.options.dataMedium': 'Medium data (5-20GB)',
    'filters.options.dataLarge': 'Mye data (20-50GB)',
    'filters.options.dataUnlimited': 'Ubegrenset data',
    'filters.options.spot': 'Spotpris',
    'filters.options.months12': '12 måneder',
    'filters.options.months24': '24 måneder',
    'filters.options.months36': '36 måneder',
    'filters.options.allTypes': 'Alle typer',
    'filters.options.allPlans': 'Alle planer',
    'filters.options.planBasic': 'Grunnpakke',
    'filters.options.planStandard': 'Standard',
    'filters.options.planPremium': 'Premium',
    'filters.options.installProfessional': 'Profesjonell installasjon',
    'filters.options.installDIY': 'Selvmontering',
    'filters.options.responseWithGuard': 'Med vaktservice',
    'filters.options.responseWithoutGuard': 'Uten vaktservice',
    'filters.options.appControl': 'App-styring',
    'filters.options.googleHome': 'Google Home',
    'filters.options.alexa': 'Alexa',
    'filters.options.appleHomeKit': 'Apple HomeKit',
    'filters.options.allServices': 'Alle tjenester',
    'filters.options.serviceRenovation': 'Renovering',
    'filters.options.serviceRepair': 'Reparasjon',
    'filters.options.serviceElectrical': 'Elektrikertjenester',
    'filters.options.servicePlumbing': 'Rørleggertjenester',
    'filters.options.servicePainting': 'Malertjenester',
    'filters.options.certified': 'Sertifisert',
    'filters.options.notCertified': 'Ikke sertifisert',
    'filters.options.cleaningHome': 'Hjemmerengjøring',
    'filters.options.cleaningOffice': 'Kontorrengjøring',
    'filters.options.cleaningDeep': 'Hovedrengjøring',
    'filters.options.cleaningRegular': 'Vanlig rengjøring',
    'filters.options.cleaningMoving': 'Flytterengjøring',
    'filters.options.equipmentIncluded': 'Utstyr inkludert',
    'filters.options.bringOwnEquipment': 'Ta med eget utstyr',

    // Sorting
    'sorting.bestMatch': 'Best match',
    'sorting.priceLowToHigh': 'Lav til høy',
    'sorting.priceHighToLow': 'Høy til lav',
    'sorting.providerAZ': 'Leverandør: A-Å',
    'sorting.providerZA': 'Leverandør: Å-A',
    'sorting.newest': 'Nyeste først',
    'sorting.oldest': 'Eldste først',
    'sorting.rateLowToHigh': 'Rente: lav til høy',
    'sorting.rateHighToLow': 'Rente: høy til lav',
    'sorting.dataHighToLow': 'Data: høy til lav',
    'sorting.speedHighToLow': 'Hastighet: høy til lav',

     // About
     'about.hero.title': 'Smart sammenligning av daglige tjenester',
     'about.hero.subtitle': 'Vi hjelper nordmenn med å spare penger på strøm, internett, mobil, forsikring og lån.',
      
      // Vision section
      'about.vision.title': 'Vår visjon',
      'about.vision.smart': 'Smart sammenligning',
      'about.vision.smartDescription': 'Vi bruker teknologi for å finne de beste tilbudene for deg.',
      'about.vision.smart.title': 'Smart sammenligning',
      'about.vision.smart.description': 'Vi bruker teknologi for å finne de beste tilbudene for deg.',
      'about.vision.free': 'Helt gratis',
      'about.vision.freeDescription': 'Vår tjeneste er 100% gratis uten skjulte kostnader.',
      'about.vision.free.title': 'Helt gratis',
      'about.vision.free.description': 'Vår tjeneste er 100% gratis uten skjulte kostnader.',
      'about.vision.fast': 'Raskt og enkelt',
      'about.vision.fastDescription': 'Få tilbud på få minutter, ikke timer eller dager.',
      'about.vision.fast.title': 'Raskt og enkelt',
      'about.vision.fast.description': 'Få tilbud på få minutter, ikke timer eller dager.',
      
      // Unique features
      'about.unique.title': 'Hva gjør oss unike',
      'about.unique.free': 'Helt gratis tjeneste',
      'about.unique.freeDescription': 'Vi tar aldri betalt for våre tjenester - alt er 100% gratis.',
      'about.unique.free.title': 'Helt gratis tjeneste',
      'about.unique.free.description': 'Vi tar aldri betalt for våre tjenester - alt er 100% gratis.',
      'about.unique.transparent': 'Full transparens',
      'about.unique.transparentDescription': 'Ingen skjulte kostnader eller binding - alt er åpent og ærlig.',
      'about.unique.transparent.title': 'Full transparens',
      'about.unique.transparent.description': 'Ingen skjulte kostnader eller binding - alt er åpent og ærlig.',
      'about.unique.personal': 'Personlig service',
      'about.unique.personalDescription': 'Våre eksperter hjelper deg med å finne det beste tilbudet.',
      'about.unique.personal.title': 'Personlig service',
      'about.unique.personal.description': 'Våre eksperter hjelper deg med å finne det beste tilbudet.',
      'about.unique.response': 'Rask respons',
      'about.unique.responseDescription': 'Vi svarer raskt og holder deg oppdatert hele veien.',
      'about.unique.fast.title': 'Rask respons',
      'about.unique.fast.description': 'Vi svarer raskt og holder deg oppdatert hele veien.',
      
      // Values
      'about.values.title': 'Våre verdier',
      'about.values.honesty': 'Ærlighet',
      'about.values.honestyDescription': 'Vi er alltid ærlige om fordeler og ulemper ved hvert tilbud.',
      'about.values.honesty.title': 'Ærlighet',
      'about.values.honesty.description': 'Vi er alltid ærlige om fordeler og ulemper ved hvert tilbud.',
      'about.values.efficiency': 'Effektivitet',
      'about.values.efficiencyDescription': 'Vi sparer tid for deg ved å gjøre sammenligningen raskt og enkelt.',
      'about.values.efficiency.title': 'Effektivitet',
      'about.values.efficiency.description': 'Vi sparer tid for deg ved å gjøre sammenligningen raskt og enkelt.',
      'about.values.quality': 'Kvalitet',
      'about.values.qualityDescription': 'Vi sikrer at alle tilbud vi presenterer holder høy kvalitet.',
      'about.values.quality.title': 'Kvalitet',
      'about.values.quality.description': 'Vi sikrer at alle tilbud vi presenterer holder høy kvalitet.',
      'about.values.focus': 'Kundefokus',
      'about.values.focusDescription': 'Dine behov står alltid i sentrum for alt vi gjør.',
      'about.values.customer.title': 'Kundefokus',
      'about.values.customer.description': 'Dine behov står alltid i sentrum for alt vi gjør.',
      
      // Team
      'about.team.title': 'Team bak PrisPilot',
      'about.team.subtitle': 'Teamet bak PrisPilot',
      'about.team.description': 'Vi er et stort Team, dedikert med solid bakgrunn fra teknologi og finans. Vår lidenskap er å hjelpe nordmenn med å spare penger på daglige tjenester – enkelt, trygt og effektivt.',
      
      // CTA
      'about.cta.readyToSave': 'Klar til å spare penger?',
      'about.cta.getPersonalized': 'Få personlige tilbud i dag og begynn å spare på dine månedlige utgifter.',
      'about.cta.getQuote': 'Få tilbud',
      'about.cta.benefits': '✓ Gratis og uforpliktende ✓ Svar innen 24 timer',
      'about.cta.title': 'Klar til å spare penger?',
      'about.cta.subtitle': 'Få personlige tilbud i dag og begynn å spare på dine månedlige utgifter.',
      'about.cta.button': 'Få tilbud',
      'about.cta.features1': 'Gratis og uforpliktende',
      'about.cta.features2': 'Svar innen 24 timer',

     // Contact
     'contact.title': 'Kontakt oss',
     'contact.subtitle': 'Vi er her for å hjelpe deg med alle dine spørsmål',
     
     // Contact info
     'contact.info.title': 'Kontaktinformasjon',
     'contact.info.phone': 'Telefon',
     'contact.info.phoneValue': '+47 123 45 678',
     'contact.info.email': 'E-post',
     'contact.info.emailValue': 'kontakt@prispilot.no',
     'contact.info.address': 'Adresse',
     'contact.info.addressValue': 'Gullhaug Torg 2, 0484 Oslo',
     'contact.info.hours': 'Åpningstider',
     'contact.info.hoursValue': 'Mandag - Fredag: 09:00 - 17:00',
     
     // Quick help
     'contact.info.quickHelp': 'Trenger du rask hjelp?',
     'contact.info.quickHelpText': 'Bruk vårt kontaktskjema eller ring oss direkte for øyeblikkelig assistanse.',
     'contact.info.startComparison': 'Start sammenligning nå',
     
     // Contact form
     'contact.form.title': 'Send oss en melding',
     'contact.form.name': 'Navn',
     'contact.form.namePlaceholder': 'Ditt fulle navn',
     'contact.form.email': 'E-post',
     'contact.form.emailPlaceholder': 'din@epost.no',
     'contact.form.phone': 'Telefon',
     'contact.form.phonePlaceholder': 'Ditt telefonnummer',
     'contact.form.message': 'Melding',
     'contact.form.messagePlaceholder': 'Skriv din melding her...',
      'contact.form.submit': 'Send melding',
      'contact.form.submitting': 'Sender...',
      'contact.form.nameRequired': 'Navn er påkrevd',
      'contact.form.emailRequired': 'E-post er påkrevd',
      'contact.form.emailInvalid': 'Ugyldig e-postadresse',
      'contact.form.messageRequired': 'Melding er påkrevd',
      'contact.toasts.success.title': 'Melding sendt!',
      'contact.toasts.success.description': 'Takk for din henvendelse. Vi vil kontakte deg så snart som mulig.',
      'contact.toasts.error.title': 'Noe gikk galt',
     'contact.toasts.error.description': 'Beklager, vi kunne ikke sende meldingen din. Prøv igjen senere.',

     // Multi-step Quote Form
     'quote.title': 'Få tilbud fra flere leverandører',
     'quote.step': 'Steg',
     'quote.of': 'av',
     'quote.fields.name': 'Navn *',
     'quote.fields.namePlaceholder': 'Ditt fulle navn',
     'quote.fields.phone': 'Telefonnummer *',
     'quote.fields.phonePlaceholder': 'Ditt telefonnummer',
     'quote.fields.email': 'E-post (valgfritt)',
     'quote.fields.emailPlaceholder': 'din@epost.no',
     'quote.fields.userType': 'Brukertype',
     'quote.fields.private': 'Privat',
     'quote.fields.business': 'Bedrift',
     'quote.service.title': 'Hvilken tjeneste vil du sammenligne? *',
     'quote.service.placeholder': 'Velg tjeneste',
     'quote.provider.title': 'Hvem er din nåværende leverandør? *',
     'quote.provider.placeholder': 'Velg leverandør',
     'quote.summary.title': 'Oppsummering',
     'quote.consent': 'Jeg samtykker til at PrisPilot kontakter meg med tilbud fra forskjellige leverandører. Jeg forstår at mine opplysninger vil bli delt med relevante partnere for å kunne gi meg de beste tilbudene.',
     'quote.back': 'Tilbake',
     'quote.next': 'Neste',
     'quote.submit': 'Send inn',
     'quote.submitting': 'Sender...',
     'quote.validation.fields': 'Påkrevde felt mangler',
     'quote.validation.namePhone': 'Navn og telefonnummer må fylles ut',
     'quote.validation.service': 'Tjeneste må velges',
     'quote.validation.serviceDesc': 'Du må velge hvilken tjeneste du vil sammenligne',
     'quote.validation.provider': 'Leverandør må velges',
     'quote.validation.providerDesc': 'Du må velge din nåværende leverandør',
     'quote.validation.consent': 'Samtykke påkrevd',
     'quote.validation.consentDesc': 'Du må samtykke til våre vilkår for å fortsette',
     'quote.success.title': 'Takk for din henvendelse!',
     'quote.success.desc': 'Vi vil kontakte deg snart med tilpassede tilbud.',
     'quote.error.title': 'Noe gikk galt',
     'quote.error.desc': 'Beklager, vi kunne ikke behandle forespørselen din. Prøv igjen senere.',

     // Offer related keys
     'offer.speed': 'Hastighet',
     'offer.getQuote': 'Få tilbud',
     'offer.monthly': 'kr/mnd',
     'offer.data': 'Data',
     'offer.markup': 'Påslag',
     'offer.municipality': 'Kommune',
     'offer.type': 'Type',
     'offer.switchNow': 'Bytt nå',
     'offer.calculatedFor': 'Beregnet for',
     'offer.annualConsumption': 'årlig forbruk',

     // Power related keys
     'power.offersFound': 'tilbud funnet',
     'power.estimated': 'Estimert',
     'power.kWh': 'kWh',
     'power.loading': 'Laster...',
    'offer.contactForPrice': 'Kontakt for pris',
    'offer.unlimited': 'Ubegrenset',
     'contact.form.required': '*',

     // Footer
     'footer.description': 'Prisene vi viser er hentet fra åpne kilder og leverandørenes egne nettsider. Vi gjør vårt ytterste for å holde informasjonen oppdatert, men anbefaler alltid at du selv verifiserer detaljer før du inngår en avtale.',
     'footer.help': 'Ønsker du personlig hjelp? Meld deg gjerne på, så vurderer vi alternativene for deg og finner det mest kostnadseffektive og passende tilbudet basert på dine behov.',
     'footer.services': 'Tjenester',
     'footer.electricity': 'Strøm',
     'footer.internet': 'Internett',
     'footer.mobile': 'Mobil',
     'footer.tv': 'TV-pakker',
     'footer.insurance': 'Forsikring',
     'footer.loans': 'Lån',
     'footer.alarm': 'Boligalarm',
     'footer.cleaning': 'Renhold',
     'footer.handymen': 'Håndverkere',
     'footer.legal': 'Juridisk',
     'footer.privacy': 'Personvernpolicy',
     'footer.terms': 'Vilkår for bruk',
     'footer.about': 'Om PrisPilot',
     'footer.contact': 'Kontakt oss',
     'footer.copyright': '© 2024 PrisPilot. Alle rettigheter forbeholdt.',
     'footer.personalHelp': 'Ønsker du personlig hjelp? Meld deg gjerne på!',

    // Handworkmen
    'handworkmen.selectCategory': 'Velg type håndverk',
    'handworkmen.all': 'Alle',
    'handworkmen.allDescription': 'Vis alle håndverkere',
    'handworkmen.renovation': 'Renovering',
    'handworkmen.renovationDescription': 'Komplett renovering',
    'handworkmen.repair': 'Reparasjon',
    'handworkmen.repairDescription': 'Akutte reparasjoner',
    'handworkmen.electrical': 'Elektro',
    'handworkmen.electricalDescription': 'Elektriske arbeider',
    'handworkmen.plumbing': 'Rørlegger',
    'handworkmen.plumbingDescription': 'Rørleggerarbeid',
    'handworkmen.painting': 'Maleri',
    'handworkmen.paintingDescription': 'Maling og lakering',

    // Cleaning
    'cleaning.selectCategory': 'Velg type rengjøring',
    'cleaning.all': 'Alle',
    'cleaning.allDescription': 'Vis alle rengjøringstyper',
    'cleaning.home': 'Bolig',
    'cleaning.homeDescription': 'Hjemmerengjøring',
    'cleaning.office': 'Kontor',
    'cleaning.officeDescription': 'Kontorrenhold',
    'cleaning.deep': 'Storrengjøring',
    'cleaning.deepDescription': 'Grundig rengjøring',
    'cleaning.regular': 'Fast renhold',
    'cleaning.regularDescription': 'Regelmessig rengjøring',
    'cleaning.moving': 'Flytterengjøring',
    'cleaning.movingDescription': 'Rengjøring ved utflytting',

    // Cookie
    'cookie.title': 'Vi bruker informasjonskapsler',
    'cookie.content': 'Vi bruker informasjonskapsler for å forbedre din opplevelse på vårt nettsted.',
    'cookie.accept': 'Godta alle',
    'cookie.decline': 'Avvis',
    'cookie.privacyPolicy': 'Personvernerklæring',
    'cookie.termsOfUse': 'Bruksvilkår',

    // Common
    'common.loading': 'Laster...',
    'common.error': 'Feil',
    'common.retry': 'Prøv igjen',
    'common.close': 'Lukk',
    'common.save': 'Lagre',
    'common.cancel': 'Avbryt',
    'common.yes': 'Ja',
    'common.no': 'Nei',
    'common.ok': 'OK',
    'common.search': 'Søk',
    'common.filter': 'Filtrer',
    'common.sort': 'Sorter',
    'common.clear': 'Tøm',
    'common.apply': 'Bruk',
    'common.reset': 'Tilbakestill'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.more': 'More',
    'nav.aboutPrisPilot': 'About PrisPilot',
    'nav.howItWorks': 'How it works',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.settings': 'Settings',
    'nav.language': 'Language',
    'nav.theme': 'Theme',

    // Navigation specific
    'navigation.backToOverview': 'Back to overview',
    'navigation.compareAndFind': 'Compare and find best offers',

    // Terms
    'terms.backToHome': 'Back to home',
    'terms.title': 'Terms and Conditions',
    'terms.lastUpdated': 'Last updated',
    'terms.acceptance.title': 'Acceptance of Terms',
    'terms.acceptance.content': 'By using PrisPilot, you accept these terms and conditions.',
    'terms.serviceDescription.title': 'Service Description',
    'terms.serviceDescription.intro': 'PrisPilot offers the following services:',
    'terms.serviceDescription.feature1': 'Price comparison of electricity, mobile, internet and other services',
    'terms.serviceDescription.feature2': 'Offer retrieval and mediation to third-party providers',
    'terms.serviceDescription.feature3': 'Information and guidance about various products and services',
    'terms.userResponsibility.title': 'User Responsibility',
    'terms.userResponsibility.intro': 'As a user, you are responsible for:',
    'terms.userResponsibility.item1': 'Providing correct and updated information',
    'terms.userResponsibility.item2': 'Using the service in accordance with applicable laws and regulations',
    'terms.userResponsibility.item3': 'Not misusing or manipulating the service',
    'terms.userResponsibility.item4': 'Protecting your own login credentials',
    'terms.informationAccuracy.title': 'Information Accuracy',
    'terms.informationAccuracy.content': 'We strive to keep all information updated and accurate, but cannot guarantee complete accuracy at all times.',
    'terms.thirdPartyServices.title': 'Third Party Services',
    'terms.thirdPartyServices.content': 'When using our services, you may be redirected to third-party providers. We are not responsible for their terms or services.',
    'terms.limitationOfLiability.title': 'Limitation of Liability',
    'terms.limitationOfLiability.content': 'PrisPilot cannot be held liable for indirect losses or damages resulting from the use of our services.',
    'terms.changes.title': 'Changes to Terms',
    'terms.changes.content': 'We reserve the right to change these terms. Changes will be published on this page.',
    'terms.contact.title': 'Contact',
    'terms.contact.intro': 'For questions about the terms, you can contact us:',
    'terms.contact.email': 'Email',
    'terms.contact.phone': 'Phone',
    'terms.applicableLaw.title': 'Applicable Law',
    'terms.applicableLaw.content': 'These terms are subject to Norwegian law and any disputes shall be resolved by Norwegian courts.',

    // Privacy
    'privacy.backToHome': 'Back to home',
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated',
    'privacy.introduction.title': 'Introduction',
    'privacy.introduction.content': 'This privacy policy explains how PrisPilot collects, uses and protects your personal information.',
    'privacy.dataCollection.title': 'Data Collection',
    'privacy.dataCollection.userProvided.title': 'Information you provide',
    'privacy.dataCollection.userProvided.item1': 'Name and contact information',
    'privacy.dataCollection.userProvided.item2': 'Usage data and preferences',
    'privacy.dataCollection.userProvided.item3': 'Communication with customer service',
    'privacy.dataCollection.automatic.title': 'Automatically collected data',
    'privacy.dataCollection.automatic.item1': 'IP address and device info',
    'privacy.dataCollection.automatic.item2': 'Browsing data and cookies',
    'privacy.dataCollection.automatic.item3': 'Usage patterns and preferences',
    'privacy.dataUsage.title': 'Use of Data',
    'privacy.dataUsage.intro': 'We use your data for the following purposes:',
    'privacy.dataUsage.item1': 'To deliver and improve our services',
    'privacy.dataUsage.item2': 'To personalize offers and recommendations',
    'privacy.dataUsage.item3': 'To communicate with you about our services',
    'privacy.dataUsage.item4': 'To fulfill legal obligations',
    'privacy.dataUsage.item5': 'To analyze and improve user experience',
    'privacy.dataSharing.title': 'Data Sharing',
    'privacy.dataSharing.intro': 'We may share your information with:',
    'privacy.dataSharing.item1': 'Partners and suppliers who provide services on our behalf',
    'privacy.dataSharing.item2': 'Third-party providers for offer mediation',
    'privacy.dataSharing.item3': 'Authorities when required by law',
    'privacy.dataSharing.item4': 'Other parties with your explicit consent',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.intro': 'We use cookies to:',
    'privacy.cookies.item1': 'Remember your preferences and settings',
    'privacy.cookies.item2': 'Analyze how the website is used',
    'privacy.cookies.item3': 'Customize content and advertisements',
    'privacy.cookies.item4': 'Improve website security',
    'privacy.cookies.control': 'You can control cookies through your browser settings.',
    'privacy.dataSecurity.title': 'Data Security',
    'privacy.dataSecurity.content': 'We implement technical and organizational measures to protect your personal information against unauthorized access, loss or misuse.',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.intro': 'You have the following rights regarding your personal information:',
    'privacy.rights.item1': 'Right to access what information we have about you',
    'privacy.rights.item2': 'Right to correct inaccurate or incomplete information',
    'privacy.rights.item3': 'Right to deletion of your personal information',
    'privacy.rights.item4': 'Right to restrict processing of your information',
    'privacy.rights.item5': 'Right to data portability',
    'privacy.rights.item6': 'Right to object to processing',
    'privacy.rights.item7': 'Right to withdraw consent',
    'privacy.dataRetention.title': 'Data Retention',
    'privacy.dataRetention.content': 'We retain your personal information as long as necessary for the purposes described in this statement, or as required by law.',
    'privacy.policyChanges.title': 'Privacy Policy Changes',
    'privacy.policyChanges.content': 'We may update this privacy policy from time to time. Changes will be published on this page.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.intro': 'For privacy questions, you can contact us:',
    'privacy.contact.email': 'Email',
    'privacy.contact.phone': 'Phone',
    'privacy.contact.address': 'Address',
    'privacy.contact.complaint': 'You can also complain to the Data Protection Authority if you believe we are processing your personal information incorrectly.',

    // Hero Section
     'hero.title': 'Save money on electricity, mobile and insurance – without lifting a finger.',
     'hero.subtitle': 'We do the work for you – you get the best prices without having to compare yourself. The service is completely free, without commitment and fully GDPR secured.',
     'hero.trust.free': '100% free',
     'hero.trust.nobinding': 'No commitment',
     'hero.trust.secure': 'Your data is safe with us',
     'hero.search.placeholder': 'Search for provider...',
     'hero.form.title': 'Get offers in minutes',
     'hero.form.subtitle': 'Fill in name and phone, and choose what you want to save on. We send you suggestions based on your situation – completely non-binding.',
     'hero.form.usertype': 'Select user type',
     'hero.form.private': 'Private',
     'hero.form.business': 'Business',
     'hero.form.name': 'Your Name',
     'hero.form.phone': 'Phone Number',
     'hero.form.submit': 'GET OFFERS FREE',
     'hero.form.submitting': 'Sending...',
     'hero.form.consent': 'By signing up you accept our',
     'hero.form.terms': 'terms and privacy policy',
     'hero.form.privacy': 'terms and privacy policy',

    // Index page
     'index.partners.title': 'Our partners',
     'index.partners.subtitle': 'We compare offers from leading providers',
     'index.services.title': 'All services',
     'index.services.subtitle': 'We compare prices in all these areas',
     'index.services.viewPrices': 'See prices',

    // Categories
     'categories.strom.title': 'Electricity',
     'categories.strom.description': 'Compare electricity prices',
     'categories.mobil.title': 'Mobile',
     'categories.mobil.description': 'Find best mobile subscription',
     'categories.forsikring.title': 'Insurance',
     'categories.forsikring.description': 'Compare insurances',
     'categories.internett.title': 'Internet',
     'categories.internett.description': 'Find best internet offer',
     'categories.lan.title': 'Loan',
     'categories.lan.description': 'Compare loan offers',
     'categories.boligalarm.title': 'Home Alarm',
     'categories.boligalarm.description': 'Find best security system',
     'categories.tvPakker.title': 'TV Packages',
     'categories.tvPakker.description': 'Compare TV packages',
     'categories.handverkere.title': 'Handymen',
     'categories.handverkere.description': 'Find qualified handymen',
     'categories.renhold.title': 'Cleaning',
     'categories.renhold.description': 'Find cleaning services',

    // Insurance specific
    'insurance.selectCategory': 'Select category',
    'insurance.all': 'All',
    'insurance.allDescription': 'Show all insurance',
    'insurance.home': 'Home Insurance',
    'insurance.homeDescription': 'Insurance for home and contents',
    'insurance.vehicle': 'Car Insurance',
    'insurance.vehicleDescription': 'Insurance for car and motorcycle',
    'insurance.person': 'Personal Insurance',
    'insurance.personDescription': 'Life and personal insurance',
    'insurance.pets': 'Pet Insurance',
    'insurance.petsDescription': 'Insurance for pets',

    // TV packages specific
    'tv.selectCategory': 'Select category',
    'tv.all': 'All',
    'tv.allDescription': 'Show all TV packages',
    'tv.standard': 'Standard',
    'tv.standardDescription': 'Basic TV packages',
    'tv.streaming': 'Streaming',
    'tv.streamingDescription': 'Streaming services and on-demand',
    'tv.sport': 'Sport',
    'tv.sportDescription': 'Sports packages and channels',
    'tv.flexible': 'Flexible',
    'tv.flexibleDescription': 'Flexible TV solutions',
    'tv.cabin': 'Cabin',
    'tv.cabinDescription': 'TV packages for cabin',
    'tv.combo': 'Combo Packages',
    'tv.comboDescription': 'TV, internet and phone',
    'tv.extras': 'Extras',
    'tv.extrasDescription': 'Additional services and premium channels',

    // Loan specific
    'loan.selectCategory': 'Select category',
    'loan.all': 'All',
    'loan.showAllOffers': 'Show all loan offers',
    'loan.unsecuredLoans': 'Unsecured Loans',
    'loan.consumerLoan': 'Consumer loan without security',
    'loan.refinanceDebt': 'Refinancing',
    'loan.refinancing': 'Consolidate existing debt',
    'loan.securedHomeLoan': 'Home Loan',
    'loan.homeLoan': 'Loan secured by home',
    'loan.carLoan': 'Car Loan',
    'loan.vehicleFinancing': 'Vehicle financing',

    // Alarm specific
    'alarm.selectCategory': 'Select category',
    'alarm.all': 'All',
    'alarm.allDescription': 'Show all alarm systems',
    'alarm.intrusion': 'Intrusion',
    'alarm.intrusionDescription': 'Burglary alarm and monitoring',
    'alarm.fire': 'Fire',
    'alarm.fireDescription': 'Fire alarm and smoke detectors',
    'alarm.water': 'Water',
    'alarm.waterDescription': 'Water leakage and moisture detectors',
    'alarm.camera': 'Camera',
    'alarm.cameraDescription': 'Surveillance cameras',
    'alarm.smart': 'Smart',
    'alarm.smartDescription': 'Smart alarm systems',

     // How it works
     'howItWorks.title': 'How PrisPilot works',
     'howItWorks.subtitle': 'Three simple steps to better deals and lower prices on electricity, mobile, internet and insurance.',
     'howItWorks.step1.number': 'STEP 1',
     'howItWorks.step1.title': 'Tell us about your needs',
     'howItWorks.step1.description': 'Fill out a simple form with information about your current situation and preferences.',
     'howItWorks.step1.detail1': 'Choose which service you want to compare',
     'howItWorks.step1.detail2': 'Provide your current provider and contract',
     'howItWorks.step1.detail3': 'Share contact information for personal offers',
     'howItWorks.step2.number': 'STEP 2',
     'howItWorks.step2.title': 'We find the best offers',
     'howItWorks.step2.description': 'Our experts compare hundreds of offers from leading providers to find what suits you best.',
     'howItWorks.step2.detail1': 'Comparison of prices and terms',
     'howItWorks.step2.detail2': 'Assessment based on your specific needs',
     'howItWorks.step2.detail3': 'Quality control of all recommendations',
     'howItWorks.step3.number': 'STEP 3',
     'howItWorks.step3.title': 'You receive personal recommendations',
     'howItWorks.step3.description': 'Get tailored offers directly by phone or email, completely free and without obligations.',
     'howItWorks.step3.detail1': 'Personal offers tailored to your needs',
     'howItWorks.step3.detail2': 'Transparent comparison of alternatives',
     'howItWorks.step3.detail3': 'Support throughout the entire process',
     'howItWorks.cta.title': 'Ready to save money?',
     'howItWorks.cta.subtitle': 'Let us help you find better deals on your daily services.',
     'howItWorks.cta.button': 'Get offers for free',

    // Services in header
    'services.strom': 'Electricity',
    'services.internett': 'Internet',
    'services.mobil': 'Mobile',
    'services.tv-pakker': 'TV Packages',
    'services.forsikring': 'Insurance',
    'services.lan': 'Loans',
    'services.boligalarm': 'Home Alarm',
    'services.handverkere': 'Handymen',
    'services.renhold': 'Cleaning',

    // Internet specific
    'internet.selectCategory': 'Select category',
    'internet.all': 'All',
    'internet.allDescription': 'Show all internet subscriptions',
    'internet.fiber': 'Fiber',
    'internet.fiberDescription': 'High-speed fiber internet',
    'internet.adsl': 'ADSL',
    'internet.adslDescription': 'ADSL-based internet',
    'internet.mobile': 'Mobile internet',
    'internet.mobileDescription': 'Internet via mobile network',
    'internet.business': 'Business',
    'internet.businessDescription': 'Internet for businesses',

    // CTA
    'cta.getOffers': 'Get Offers',
    'cta.compare': 'Compare',
    'cta.signUp': 'Sign Up',
    'cta.getQuote': 'Get Quote',
    'cta.contactProvider': 'Contact Provider',
    'cta.viewDetails': 'View Details',
    'cta.selectOffer': 'Select Offer',
    'cta.backToTop': 'Back to Top',

    // Categories
    'categoryName.mobil': 'Mobile',
    'categoryName.strom': 'Electricity',
    'categoryName.internett': 'Internet',
    'categoryName.forsikring': 'Insurance',
    'categoryName.lan': 'Loans',
    'categoryName.boligalarm': 'Home Alarm',
    'categoryName.tv-pakker': 'TV Packages',
    'categoryName.handverkere': 'Handymen',
    'categoryName.renhold': 'Cleaning',

    // Category specific
    'category.viewPrices': 'View Prices',

    // Mobile specific
    'mobile.selectCategory': 'Select category',
    'mobile.all': 'All',
    'mobile.allDescription': 'Show all mobile subscriptions',
    'mobile.lowPrice': 'Low Price',
    'mobile.lowPriceDescription': 'Affordable subscriptions',
    'mobile.family': 'Family',
    'mobile.familyDescription': 'Family subscriptions',
    'mobile.unlimited': 'Unlimited',
    'mobile.unlimitedDescription': 'Unlimited data',
    'mobile.business': 'Business',
    'mobile.businessDescription': 'Business subscriptions',

    // Electricity specific
    'electricity.selectCategory': 'Filter by contract type',
    'electricity.all': 'All',
    'electricity.allDescription': 'Show all electricity contracts',
    'electricity.spot': 'Spot Price',
    'electricity.spotDescription': 'Variable prices follow the market',
    'electricity.fixed': 'Fixed Price',
    'electricity.fixedDescription': 'Fixed price for periods',
    'electricity.green': 'Green Energy',
    'electricity.greenDescription': 'Environmentally friendly alternatives',
    'electricity.business': 'Business',
    'electricity.businessDescription': 'Electricity for businesses',
    'electricity.variableDescription': 'Variable price without commitment',
    'electricity.residentialDescription': 'Electricity for homes and apartments',
    'electricity.cabinDescription': 'Electricity for cabins and holiday homes',

    // Power contract types
    'power.contractTypes.all': 'All',
    'power.contractTypes.spot': 'Spot Price',
    'power.contractTypes.fixed': 'Fixed Price',
    'power.contractTypes.variable': 'Variable',
    'power.contractTypes.green': 'Green Energy',
    'power.contractTypes.residential': 'Residential',
    'power.contractTypes.cabin': 'Cabin',

    // Power related
    'power.howMuchElectricity': 'How much electricity do you use annually?',
    'power.averageConsumption': 'Average annual consumption',
    'power.selectMunicipality': 'Select your municipality',
    'power.searchMunicipality': 'Search for municipality...',
    'power.filterContractType': 'Filter by contract type',
    'power.showMatchingOffers': 'Show {{count}} offers',
    'power.resetFilters': 'Reset filters',

    // Filters
    'filters.title': 'Filters',
    'filters.clear': 'Clear',
    'filters.sort': 'Sort',
    'filters.offersFound': 'offers found',
    'filters.labels.provider': 'Provider',
    'filters.labels.speed': 'Speed',
    'filters.labels.price': 'Price',
    'filters.labels.operator': 'Operator',
    'filters.labels.supplier_name': 'Supplier',
    'filters.labels.municipality': 'Municipality',
    'filters.labels.priceElectricity': 'Price (øre/kWh)',
    'filters.labels.contract_length': 'Contract period',
    'filters.labels.data_category': 'Data category',
    'filters.labels.insurance_type': 'Insurance type',
    'filters.labels.monthly_premium': 'Monthly premium',
    'filters.labels.effective_rate': 'Effective rate (%)',
    'filters.labels.monthly_price': 'Monthly price',
    'filters.labels.plan_type': 'Plan type',
    'filters.labels.alarm_types': 'Alarm types',
    'filters.labels.installation_type': 'Installation',
    'filters.labels.response_service': 'Response service',
    'filters.labels.smart_features': 'Smart features',
    'filters.labels.channels_count': 'Number of channels',
    'filters.labels.hourly_rate': 'Hourly rate',
    'filters.labels.service_type': 'Service type',
    'filters.labels.certification': 'Certification',
    'filters.labels.cleaning_type': 'Cleaning type',
    'filters.labels.equipment_included': 'Equipment included',
    'filters.options.allProviders': 'All providers',
    'filters.options.selectProvider': 'Select provider',
    'filters.options.all': 'All',
    'filters.options.search': 'Search...',
    'filters.options.searchHint': 'Enter municipality name',
    'filters.options.dataSmall': 'Small data (under 5GB)',
    'filters.options.dataMedium': 'Medium data (5-20GB)',
    'filters.options.dataLarge': 'Large data (20-50GB)',
    'filters.options.dataUnlimited': 'Unlimited data',
    'filters.options.spot': 'Spot price',
    'filters.options.months12': '12 months',
    'filters.options.months24': '24 months',
    'filters.options.months36': '36 months',
    'filters.options.allTypes': 'All types',
    'filters.options.allPlans': 'All plans',
    'filters.options.planBasic': 'Basic plan',
    'filters.options.planStandard': 'Standard',
    'filters.options.planPremium': 'Premium',
    'filters.options.installProfessional': 'Professional installation',
    'filters.options.installDIY': 'Self-installation',
    'filters.options.responseWithGuard': 'With guard service',
    'filters.options.responseWithoutGuard': 'Without guard service',
    'filters.options.appControl': 'App control',
    'filters.options.googleHome': 'Google Home',
    'filters.options.alexa': 'Alexa',
    'filters.options.appleHomeKit': 'Apple HomeKit',
    'filters.options.allServices': 'All services',
    'filters.options.serviceRenovation': 'Renovation',
    'filters.options.serviceRepair': 'Repair',
    'filters.options.serviceElectrical': 'Electrical services',
    'filters.options.servicePlumbing': 'Plumbing services',
    'filters.options.servicePainting': 'Painting services',
    'filters.options.certified': 'Certified',
    'filters.options.notCertified': 'Not certified',
    'filters.options.cleaningHome': 'Home cleaning',
    'filters.options.cleaningOffice': 'Office cleaning',
    'filters.options.cleaningDeep': 'Deep cleaning',
    'filters.options.cleaningRegular': 'Regular cleaning',
    'filters.options.cleaningMoving': 'Moving cleaning',
    'filters.options.equipmentIncluded': 'Equipment included',
    'filters.options.bringOwnEquipment': 'Bring own equipment',

    // Sorting
    'sorting.bestMatch': 'Best match',
    'sorting.priceLowToHigh': 'Low to high',
    'sorting.priceHighToLow': 'High to low',
    'sorting.providerAZ': 'Provider: A-Z',
    'sorting.providerZA': 'Provider: Z-A',
    'sorting.newest': 'Newest first',
    'sorting.oldest': 'Oldest first',
    'sorting.rateLowToHigh': 'Rate: low to high',
    'sorting.rateHighToLow': 'Rate: high to low',
    'sorting.dataHighToLow': 'Data: high to low',
    'sorting.speedHighToLow': 'Speed: high to low',

     // About
     'about.hero.title': 'Smart comparison of daily services',
     'about.hero.subtitle': 'We help Norwegians save money on electricity, internet, mobile, insurance and loans.',
      
      // Vision section
      'about.vision.title': 'Our vision',
      'about.vision.smart': 'Smart comparison',
      'about.vision.smartDescription': 'We use technology to find the best offers for you.',
      'about.vision.smart.title': 'Smart comparison',
      'about.vision.smart.description': 'We use technology to find the best offers for you.',
      'about.vision.free': 'Completely free',
      'about.vision.freeDescription': 'Our service is 100% free with no hidden costs.',
      'about.vision.free.title': 'Completely free',
      'about.vision.free.description': 'Our service is 100% free with no hidden costs.',
      'about.vision.fast': 'Fast and simple',
      'about.vision.fastDescription': 'Get offers in minutes, not hours or days.',
      'about.vision.fast.title': 'Fast and simple',
      'about.vision.fast.description': 'Get offers in minutes, not hours or days.',
      
      // Unique features
      'about.unique.title': 'What makes us unique',
      'about.unique.free': 'Completely free service',
      'about.unique.freeDescription': 'We never charge for our services - everything is 100% free.',
      'about.unique.free.title': 'Completely free service',
      'about.unique.free.description': 'We never charge for our services - everything is 100% free.',
      'about.unique.transparent': 'Full transparency',
      'about.unique.transparentDescription': 'No hidden costs or commitments - everything is open and honest.',
      'about.unique.transparent.title': 'Full transparency',
      'about.unique.transparent.description': 'No hidden costs or commitments - everything is open and honest.',
      'about.unique.personal': 'Personal service',
      'about.unique.personalDescription': 'Our experts help you find the best offer.',
      'about.unique.personal.title': 'Personal service',
      'about.unique.personal.description': 'Our experts help you find the best offer.',
      'about.unique.response': 'Fast response',
      'about.unique.responseDescription': 'We respond quickly and keep you updated throughout.',
      'about.unique.fast.title': 'Fast response',
      'about.unique.fast.description': 'We respond quickly and keep you updated throughout.',
      
      // Values
      'about.values.title': 'Our values',
      'about.values.honesty': 'Honesty',
      'about.values.honestyDescription': 'We are always honest about the advantages and disadvantages of each offer.',
      'about.values.honesty.title': 'Honesty',
      'about.values.honesty.description': 'We are always honest about the advantages and disadvantages of each offer.',
      'about.values.efficiency': 'Efficiency',
      'about.values.efficiencyDescription': 'We save time for you by making comparisons quick and easy.',
      'about.values.efficiency.title': 'Efficiency',
      'about.values.efficiency.description': 'We save time for you by making comparisons quick and easy.',
      'about.values.quality': 'Quality',
      'about.values.qualityDescription': 'We ensure that all offers we present maintain high quality.',
      'about.values.quality.title': 'Quality',
      'about.values.quality.description': 'We ensure that all offers we present maintain high quality.',
      'about.values.focus': 'Customer focus',
      'about.values.focusDescription': 'Your needs are always at the center of everything we do.',
      'about.values.customer.title': 'Customer focus',
      'about.values.customer.description': 'Your needs are always at the center of everything we do.',
      
      // Team
      'about.team.title': 'Team behind PrisPilot',
      'about.team.subtitle': 'The team behind PrisPilot',
      'about.team.description': 'We are a large dedicated team with solid background from technology and finance. Our passion is to help Norwegians save money on daily services – simple, safe and effective.',
      
      // CTA
      'about.cta.readyToSave': 'Ready to save money?',
      'about.cta.getPersonalized': 'Get personal offers today and start saving on your monthly expenses.',
      'about.cta.getQuote': 'Get offers',
      'about.cta.benefits': '✓ Free and non-binding ✓ Response within 24 hours',
      'about.cta.title': 'Ready to save money?',
      'about.cta.subtitle': 'Get personal offers today and start saving on your monthly expenses.',
      'about.cta.button': 'Get offers',
      'about.cta.features1': 'Free and non-binding',
      'about.cta.features2': 'Response within 24 hours',

     // Contact
     'contact.title': 'Contact us',
     'contact.subtitle': 'We are here to help you with all your questions',
     
     // Contact info
     'contact.info.title': 'Contact information',
     'contact.info.phone': 'Phone',
     'contact.info.phoneValue': '+47 123 45 678',
     'contact.info.email': 'Email',
     'contact.info.emailValue': 'kontakt@prispilot.no',
     'contact.info.address': 'Address',
     'contact.info.addressValue': 'Gullhaug Torg 2, 0484 Oslo',
     'contact.info.hours': 'Opening hours',
     'contact.info.hoursValue': 'Monday - Friday: 09:00 - 17:00',
     
     // Quick help
     'contact.info.quickHelp': 'Need quick help?',
     'contact.info.quickHelpText': 'Use our contact form or call us directly for immediate assistance.',
     'contact.info.startComparison': 'Start comparison now',
     
     // Contact form
     'contact.form.title': 'Send us a message',
     'contact.form.name': 'Name',
     'contact.form.namePlaceholder': 'Your full name',
     'contact.form.email': 'Email',
     'contact.form.emailPlaceholder': 'your@email.com',
     'contact.form.phone': 'Phone',
     'contact.form.phonePlaceholder': 'Your phone number',
     'contact.form.message': 'Message',
     'contact.form.messagePlaceholder': 'Write your message here...',
      'contact.form.submit': 'Send message',
      'contact.form.submitting': 'Sending...',
      'contact.form.nameRequired': 'Name is required',
      'contact.form.emailRequired': 'Email is required',
      'contact.form.emailInvalid': 'Invalid email address',
      'contact.form.messageRequired': 'Message is required',
      'contact.toasts.success.title': 'Message sent!',
      'contact.toasts.success.description': 'Thank you for your inquiry. We will contact you as soon as possible.',
      'contact.toasts.error.title': 'Something went wrong',
     'contact.toasts.error.description': 'Sorry, we could not send your message. Please try again later.',

     // Multi-step Quote Form
     'quote.title': 'Get quotes from multiple providers',
     'quote.step': 'Step',
     'quote.of': 'of',
     'quote.fields.name': 'Name *',
     'quote.fields.namePlaceholder': 'Your full name',
     'quote.fields.phone': 'Phone number *',
     'quote.fields.phonePlaceholder': 'Your phone number',
     'quote.fields.email': 'Email (optional)',
     'quote.fields.emailPlaceholder': 'your@email.com',
     'quote.fields.userType': 'User type',
     'quote.fields.private': 'Private',
     'quote.fields.business': 'Business',
     'quote.service.title': 'Which service do you want to compare? *',
     'quote.service.placeholder': 'Select service',
     'quote.provider.title': 'Who is your current provider? *',
     'quote.provider.placeholder': 'Select provider',
     'quote.summary.title': 'Summary',
     'quote.consent': 'I consent to PrisPilot contacting me with offers from different providers. I understand that my information will be shared with relevant partners to provide me with the best offers.',
     'quote.back': 'Back',
     'quote.next': 'Next',
     'quote.submit': 'Submit',
     'quote.submitting': 'Submitting...',
     'quote.validation.fields': 'Required fields missing',
     'quote.validation.namePhone': 'Name and phone number must be filled in',
     'quote.validation.service': 'Service must be selected',
     'quote.validation.serviceDesc': 'You must select which service you want to compare',
     'quote.validation.provider': 'Provider must be selected',
     'quote.validation.providerDesc': 'You must select your current provider',
     'quote.validation.consent': 'Consent required',
     'quote.validation.consentDesc': 'You must consent to our terms to continue',
     'quote.success.title': 'Thank you for your inquiry!',
     'quote.success.desc': 'We will contact you soon with customized offers.',
     'quote.error.title': 'Something went wrong',
     'quote.error.desc': 'Sorry, we could not process your request. Please try again later.',

     // Offer related keys
     'offer.speed': 'Speed',
     'offer.getQuote': 'Get Quote',
     'offer.monthly': 'kr/month',
     'offer.data': 'Data',
     'offer.markup': 'Markup',
     'offer.municipality': 'Municipality',
     'offer.type': 'Type',
     'offer.switchNow': 'Switch Now',
     'offer.calculatedFor': 'Calculated for',
     'offer.annualConsumption': 'annual consumption',

     // Power related keys
     'power.offersFound': 'offers found',
     'power.estimated': 'Estimated',
     'power.kWh': 'kWh',
     'power.loading': 'Loading...',
    'offer.contactForPrice': 'Contact for price',
    'offer.unlimited': 'Unlimited',
     'contact.form.required': '*',

    // Footer
    'footer.description': 'PrisPilot helps you compare prices on electricity, mobile, internet and other services.',
    'footer.help': 'We make it easy to find the best offers and save money.',
    'footer.services': 'Services',
    'footer.electricity': 'Electricity',
    'footer.internet': 'Internet',
    'footer.mobile': 'Mobile',
    'footer.tv': 'TV Packages',
    'footer.insurance': 'Insurance',
    'footer.loans': 'Loans',
    'footer.alarm': 'Home Alarm',
    'footer.cleaning': 'Cleaning',
    'footer.handymen': 'Handymen',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2024 PrisPilot. All rights reserved.',
    'footer.personalHelp': 'Personal help',

    // Handworkmen
    'handworkmen.selectCategory': 'Select craftsman type',
    'handworkmen.all': 'All',
    'handworkmen.allDescription': 'Show all craftsmen',
    'handworkmen.renovation': 'Renovation',
    'handworkmen.renovationDescription': 'Complete renovation',
    'handworkmen.repair': 'Repair',
    'handworkmen.repairDescription': 'Emergency repairs',
    'handworkmen.electrical': 'Electrical',
    'handworkmen.electricalDescription': 'Electrical work',
    'handworkmen.plumbing': 'Plumber',
    'handworkmen.plumbingDescription': 'Plumbing work',
    'handworkmen.painting': 'Painting',
    'handworkmen.paintingDescription': 'Painting and coating',

    // Cleaning
    'cleaning.selectCategory': 'Select cleaning type',
    'cleaning.all': 'All',
    'cleaning.allDescription': 'Show all cleaning types',
    'cleaning.home': 'Home',
    'cleaning.homeDescription': 'Home cleaning',
    'cleaning.office': 'Office',
    'cleaning.officeDescription': 'Office cleaning',
    'cleaning.deep': 'Deep cleaning',
    'cleaning.deepDescription': 'Thorough cleaning',
    'cleaning.regular': 'Regular cleaning',
    'cleaning.regularDescription': 'Regular cleaning service',
    'cleaning.moving': 'Moving cleaning',
    'cleaning.movingDescription': 'Cleaning when moving out',

    // Cookie
    'cookie.title': 'We use cookies',
    'cookie.content': 'We use cookies to improve your experience on our website.',
    'cookie.accept': 'Accept all',
    'cookie.decline': 'Decline',
    'cookie.privacyPolicy': 'Privacy Policy',
    'cookie.termsOfUse': 'Terms of Use',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.reset': 'Reset'
  }
};

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const t = (key: string): string => {
    return translations[currentLanguage.code]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
